import type { Product, User } from "./types"

export const products: Product[] = [
  {
    id: "product-1",
    name: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear sound with our premium wireless headphones. Features noise cancellation and 30-hour battery life.",
    price: 199.99,
    category: "electronics",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    rating: 4.8,
    onSale: false,
  },
  {
    id: "product-2",
    name: "Slim Fit Cotton T-Shirt",
    description:
      "A comfortable, breathable cotton t-shirt with a modern slim fit design. Available in multiple colors.",
    price: 24.99,
    category: "clothing",
    image: "https://images.unsplash.com/photo-1523381294911-8d3cead13475?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    rating: 4.5,
    onSale: true,
    originalPrice: 34.99,
  },
  {
    id: "product-3",
    name: "Stainless Steel Water Bottle",
    description:
      "Keep your drinks cold for 24 hours or hot for 12 hours with this vacuum-insulated stainless steel water bottle.",
    price: 34.99,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
    rating: 4.7,
    onSale: false,
  },
  {
    id: "product-4",
    name: "Ergonomic Office Chair",
    description:
      "Work in comfort with this ergonomic office chair featuring adjustable height, lumbar support, and breathable mesh back.",
    price: 249.99,
    category: "furniture",
    image: "https://m.media-amazon.com/images/I/31hUIM4AYBL._SX300_SY300_QL70_FMwebp_.jpg",
    rating: 4.6,
    onSale: true,
    originalPrice: 299.99,
  },
  {
    id: "product-5",
    name: "Smart Fitness Tracker",
    description:
      "Track your steps, heart rate, sleep, and more with this waterproof smart fitness tracker with a 7-day battery life.",
    price: 89.99,
    category: "electronics",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1888&q=80",
    rating: 4.4,
    onSale: false,
  },
  {
    id: "product-6",
    name: "Leather Wallet",
    description: "A sleek, genuine leather wallet with RFID blocking technology to protect your cards and identity.",
    price: 49.99,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1627123288575-0afffb9849e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1173&q=80",
    rating: 4.3,
    onSale: false,
  },
  {
    id: "product-7",
    name: "Ceramic Coffee Mug Set",
    description: "Set of 4 ceramic coffee mugs with a modern design. Microwave and dishwasher safe.",
    price: 29.99,
    category: "home",
    image: "https://m.media-amazon.com/images/I/51V7XdMcqyL._SX300_SY300_QL70_FMwebp_.jpg",
    rating: 4.2,
    onSale: true,
    originalPrice: 39.99,
  },
  {
    id: "product-8",
    name: "Wireless Bluetooth Speaker",
    description:
      "Portable Bluetooth speaker with 360° sound, 12-hour battery life, and waterproof design for outdoor adventures.",
    price: 79.99,
    category: "electronics",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1631&q=80",
    rating: 4.5,
    onSale: false,
  },
  {
    id: "product-9",
    name: "Yoga Mat",
    description: "Non-slip, eco-friendly yoga mat with alignment lines for proper positioning during your practice.",
    price: 39.99,
    category: "fitness",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    rating: 4.6,
    onSale: true,
    originalPrice: 49.99,
  },
  {
    id: "product-10",
    name: "Stainless Steel Cookware Set",
    description:
      "10-piece stainless steel cookware set including pots, pans, and lids. Suitable for all cooktop types.",
    price: 199.99,
    category: "home",
    image: "https://images.unsplash.com/photo-1584990347449-a9e34ac96ac2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    rating: 4.7,
    onSale: false,
  },
  {
    id: "product-11",
    name: "Smartphone Stand",
    description: "Adjustable aluminum smartphone stand compatible with all phone sizes and tablets.",
    price: 19.99,
    category: "electronics",
    image: "https://m.media-amazon.com/images/I/415UNLwH9LL._SX300_SY300_QL70_FMwebp_.jpg",
    rating: 4.1,
    onSale: true,
    originalPrice: 24.99,
  },
  {
    id: "product-12",
    name: "Leather Crossbody Bag",
    description: "Stylish genuine leather crossbody bag with multiple compartments and adjustable strap.",
    price: 89.99,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=876&q=80",
    rating: 4.4,
    onSale: false,
  },
  {
    id: "product-13",
    name: "Mechanical Keyboard",
    description: "RGB backlit mechanical keyboard with customizable keys and tactile feedback for gaming and typing.",
    price: 129.99,
    category: "electronics",
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=880&q=80",
    rating: 4.8,
    onSale: true,
    originalPrice: 159.99,
  },
  {
    id: "product-14",
    name: "Cotton Bedding Set",
    description: "Luxurious 100% cotton bedding set including duvet cover, fitted sheet, and pillowcases.",
    price: 99.99,
    category: "home",
    image: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
    rating: 4.5,
    onSale: false,
  },
  {
    id: "product-15",
    name: "Wireless Charging Pad",
    description: "Fast wireless charging pad compatible with all Qi-enabled devices. Sleek, minimalist design.",
    price: 29.99,
    category: "electronics",
    image: "https://m.media-amazon.com/images/I/31Zivf8-2zL._SX300_SY300_QL70_FMwebp_.jpg",
    rating: 4.3,
    onSale: true,
    originalPrice: 39.99,
  },
  {
    id: "product-16",
    name: "Hiking Backpack",
    description: "Durable, water-resistant hiking backpack with multiple compartments and comfortable padded straps.",
    price: 79.99,
    category: "outdoors",
    image: "https://images.unsplash.com/photo-1622560480605-d83c661b4be1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
    rating: 4.6,
    onSale: false,
  },
]

export const users: User[] = [
  {
    id: "user-1",
    name: "Admin User",
    email: "admin@example.com",
    password: "password123",
    isAdmin: true,
  },
  {
    id: "user-2",
    name: "John Doe",
    email: "john@example.com",
    password: "password123",
    isAdmin: false,
  },
  {
    id: "user-3",
    name: "Jane Smith",
    email: "jane@example.com",
    password: "password123",
    isAdmin: false,
  },
]

